# Coded along
name: First workflow

# Controls when the workflow will run
# Allows you to run this workflow manually from the Actions tab
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Print greeting
        run: echo "Hello, world"
      - name: Print goodbye
        run: echo "Done bye"
